# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '摄像头拍照.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(751, 519)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("\n"
"QWidget {\n"
"border-image:url(C:/Users/123/Desktop/ruangong/MaskDetect-YOLOv4-PyTorch-master/pyqt5/背景.jpeg);\n"
"}\n"
"\n"
"#下面的防止背景干扰其他控件\n"
"QTextBrowser {\n"
"border-image:url();\n"
"}\n"
"QLineEdit {\n"
"border-image:url();\n"
"}\n"
"QComboBox {\n"
"border-image:url();\n"
"}\n"
"QLabel {\n"
"border-image:url();\n"
"}\n"
"QPushButton {\n"
"border-image:url();\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.labcamera = QtWidgets.QLabel(self.centralwidget)
        self.labcamera.setObjectName("labcamera")
        self.gridLayout.addWidget(self.labcamera, 0, 0, 1, 1)
        self.labresult = QtWidgets.QLabel(self.centralwidget)
        self.labresult.setObjectName("labresult")
        self.gridLayout.addWidget(self.labresult, 0, 1, 2, 3)
        self.labshot = QtWidgets.QLabel(self.centralwidget)
        self.labshot.setObjectName("labshot")
        self.gridLayout.addWidget(self.labshot, 1, 0, 2, 1)
        self.btnopencamera = QtWidgets.QPushButton(self.centralwidget)
        self.btnopencamera.setStyleSheet("QPushButton\n"
"{\n"
"background-color:blue;\n"
"color:#ffffff\n"
"font:75 13pt \"宋体\"\n"
"}")
        self.btnopencamera.setObjectName("btnopencamera")
        self.gridLayout.addWidget(self.btnopencamera, 2, 1, 1, 1)
        self.btnshot = QtWidgets.QPushButton(self.centralwidget)
        self.btnshot.setObjectName("btnshot")
        self.gridLayout.addWidget(self.btnshot, 2, 2, 1, 1)
        self.btnresult = QtWidgets.QPushButton(self.centralwidget)
        self.btnresult.setObjectName("btnresult")
        self.gridLayout.addWidget(self.btnresult, 2, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.action1 = QtWidgets.QAction(MainWindow)
        self.action1.setObjectName("action1")
        self.action2 = QtWidgets.QAction(MainWindow)
        self.action2.setObjectName("action2")
        self.action3 = QtWidgets.QAction(MainWindow)
        self.action3.setObjectName("action3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")

        self.retranslateUi(MainWindow)
        self.btnopencamera.clicked.connect(MainWindow.btnopencamera_Clicked)
        self.btnshot.clicked.connect(MainWindow.btnshot_Clicked)
        self.btnresult.clicked.connect(MainWindow.btnresult_Clicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "16小组口罩识别系统"))
        self.labcamera.setText(_translate("MainWindow", "摄像头"))
        self.labresult.setText(_translate("MainWindow", "结果图"))
        self.labshot.setText(_translate("MainWindow", "捕获图"))
        self.btnopencamera.setText(_translate("MainWindow", "开启摄像头"))
        self.btnshot.setText(_translate("MainWindow", "拍照"))
        self.btnresult.setText(_translate("MainWindow", "识别"))
        self.action1.setText(_translate("MainWindow", "摄像头实时检测"))
        self.action2.setText(_translate("MainWindow", "摄像头拍照检测"))
        self.action3.setText(_translate("MainWindow", "本地照片检测"))
        self.action_4.setText(_translate("MainWindow", "本地视频检测"))
