# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '口罩识别pyqt.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 544)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labcamera = QtWidgets.QLabel(self.centralwidget)
        self.labcamera.setGeometry(QtCore.QRect(69, 59, 181, 131))
        self.labcamera.setObjectName("labcamera")
        self.labshot = QtWidgets.QLabel(self.centralwidget)
        self.labshot.setGeometry(QtCore.QRect(69, 300, 181, 131))
        self.labshot.setObjectName("labshot")
        self.labresult = QtWidgets.QLabel(self.centralwidget)
        self.labresult.setGeometry(QtCore.QRect(350, 110, 351, 231))
        self.labresult.setObjectName("labresult")
        self.btnopencamera = QtWidgets.QPushButton(self.centralwidget)
        self.btnopencamera.setGeometry(QtCore.QRect(330, 400, 111, 41))
        self.btnopencamera.setObjectName("btnopencamera")
        self.btnshot = QtWidgets.QPushButton(self.centralwidget)
        self.btnshot.setGeometry(QtCore.QRect(480, 400, 111, 41))
        self.btnshot.setObjectName("btnshot")
        self.btnresult = QtWidgets.QPushButton(self.centralwidget)
        self.btnresult.setGeometry(QtCore.QRect(620, 400, 101, 41))
        self.btnresult.setObjectName("btnresult")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.btnopencamera.clicked.connect(MainWindow.btnopencamera_Clicked)
        self.btnshot.clicked.connect(MainWindow.btnshot_Clicked)
        self.btnresult.clicked.connect(MainWindow.btnresult_Clicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "16小组口罩识别系统"))
        self.labcamera.setText(_translate("MainWindow", "摄像头"))
        self.labshot.setText(_translate("MainWindow", "捕获图"))
        self.labresult.setText(_translate("MainWindow", "结果图"))
        self.btnopencamera.setText(_translate("MainWindow", "开启摄像头"))
        self.btnshot.setText(_translate("MainWindow", "拍照"))
        self.btnresult.setText(_translate("MainWindow", "识别"))
